# uploader.py
# This is the main script logic.
# DO NOT EDIT THIS FILE. Edit config.py and products.json instead.

import os
import json
import firebase_admin
from firebase_admin import credentials, firestore, storage

# --- Import all variables from config.py ---
try:
    from config import (
        SERVICE_ACCOUNT_KEY, 
        BUCKET_NAME, 
        LOCAL_IMAGES_PATH, 
        PRODUCTS_JSON_PATH,
        STORAGE_FOLDER,
        COLLECTION_NAMES,
        map_product_to_firestore
    )
except ImportError:
    print("❌ ERROR: 'config.py' file not found.")
    print("Please create 'config.py' and add your configuration variables.")
    exit()

def load_products_from_json(json_path):
    """Loads the product data from the specified JSON file."""
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"❌ ERROR: Products JSON file not found at: {json_path}")
        return None
    except json.JSONDecodeError:
        print(f"❌ ERROR: Could not decode JSON. Check for syntax errors in: {json_path}")
        return None

def upload_files():
    # Initialize Firebase Admin
    try:
        cred = credentials.Certificate(SERVICE_ACCOUNT_KEY)
        firebase_admin.initialize_app(cred, {
            'storageBucket': BUCKET_NAME
        })
        print("✅ Firebase initialized successfully.")
    except Exception as e:
        print(f"❌ ERROR: Failed to initialize Firebase. Check your service key file ('{SERVICE_ACCOUNT_KEY}') and bucket name ('{BUCKET_NAME}').")
        print(f"System error: {e}")
        return

    # Load product data from JSON
    products_data = load_products_from_json(PRODUCTS_JSON_PATH)
    if not products_data:
        return

    # Prepare database and storage clients
    db = firestore.client()
    bucket = storage.bucket()

    print(f"\nLoaded {len(products_data)} products. Starting upload...")

    for product in products_data:
        product_id = product.get('id')
        if not product_id:
            print("  ⚠️ WARNING: Skipping product with missing 'id'.")
            continue
            
        product_type = product.get('type')
        file_name = f"{product_id}.png"
        
        # Path to the local file
        local_file_path = os.path.join(LOCAL_IMAGES_PATH, file_name).replace("\\", "/")
        
        # Path in Firebase Storage
        storage_path = f"{STORAGE_FOLDER}/{file_name}"

        print(f"\n--- Processing: {product_id} ---")

        # --- Step 1: Upload image to Storage ---
        image_url = None
        try:
            if not os.path.exists(local_file_path):
                print(f"  ❌ FILE ERROR: File not found: {local_file_path}")
                continue # Skip this product

            blob = bucket.blob(storage_path)
            blob.upload_from_filename(local_file_path)

            # Make the file publicly accessible
            blob.make_public()
            image_url = blob.public_url
            print(f"  ✅ Image uploaded: {image_url}")

        except Exception as e:
            print(f"  ❌ STORAGE ERROR: Failed to upload image {file_name}.")
            print(f"     System error: {e}")
            continue # Skip this product

        # --- Step 2: Map data using the function from config.py ---
        try:
            firestore_data = map_product_to_firestore(product, image_url)
        except Exception as e:
            print(f"  ❌ MAPPING ERROR: Failed to map data for {product_id}.")
            print(f"     Check your 'map_product_to_firestore' function in config.py.")
            print(f"     System error: {e}")
            continue
            
        # --- Step 3: Save data to Firestore ---
        try:
            # Get collection name from config, fallback to 'default'
            collection_name = COLLECTION_NAMES.get(product_type, 'default_products')
            
            # Use .set() to make the document ID match the product ID
            db.collection(collection_name).document(product_id).set(firestore_data)
            print(f"  ✅ Saved data to Firestore (collection: {collection_name}).")

        except Exception as e:
            print(f"  ❌ FIRESTORE ERROR: Failed to save data for {product_id}.")
            print(f"     System error: {e}")

    print("\n--------------------------------------")
    print("✅ COMPLETE! All products processed.")
    print("--------------------------------------")

# Run the main function
if __name__ == "__main__":
    upload_files()